# コールバックの設定
callbacks:
  EarlyStopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 3
    mode: min
  ModelCheckpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_loss
    save_top_k: 1
    mode: min
    dirpath: "checkpoints/"
    filename: "best-checkpoint"
